// <auto-generated />
using ControleLocadoraAutomoveis.Infraestrutura.Orm.Compartilhado;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleLocadoraAutomoveis.Infraestrutura.Orm.Migrations
{
    [DbContext(typeof(ControleLocadoraAutomoveisDbContext))]
    partial class ControleLocadoraAutomoveisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControleLocadoraAutomoveis.Dominio.ModuloGrupoAutomoveis.GrupoAutomoveis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("TBGrupoAutomoveis", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "PASSEIO"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "UTILITÁRIO"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "VEÍCULO PARA PCD"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
